print("enter name")
name=input()
print("enter age")
age=int(input())
print("enter salary")
salary=float(input())
print("Hello,{} you are {} year old and getting salary {}".format(name,age,salary))
print("Hello,{1} you are {2} year old and getting salary {0}".format(name,age,salary))
print("Hello,{s} you are {a} year old and getting salary {c}".format(s="shakti",a=24,c=8787707.4))
print("Hello,%s you are %d year old and getting salary %.2f"%("bhakti",22,232234.56778686))